openapi: 3.1.0
info:
  title: Ingredients OAS
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      responses:
        200:
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ingredient"
  /ingredients/{id}:
    get:
      parameters:
        - $ref: "#/components/parameters/IdentifierPathVariable"
      responses:
        200:
          description: Ingredient by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredient"
        404:
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
              example: Ingredient not found
  /ingredients/{id}/stock:
    get:
      parameters:
        - $ref: "#/components/parameters/IdentifierPathVariable"
        - $ref: "#/components/parameters/AtQueryParameter"
        - $ref: "#/components/parameters/UnitQueryParameter"
      responses:
        200:
          description: Stock value at a specific date and unit
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockValue"
        404:
          description: Ingredient id is not found
          content:
            text/plain:
              schema:
                type: string
              example: Ingredient id is not found
        400:
          description: Missing query parameter
          content:
            text/plain:
              schema:
                type: string
              example: Either mandatory query parameter 'at' or 'unit' is not provided
  /dishes:
    get:
      responses:
        200:
          description: List of dishes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dish"
  /dishes/{id}/ingredients:
    put:
      parameters:
        - $ref: "#/components/parameters/IdentifierPathVariable"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Ingredient"
      responses:
        200:
          description: Updated list of ingredients for the dish
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ingredient"
        400:
          description: Request body is missing
          content:
            text/plain:
              schema:
                type: string
              example: Request body is required
        404:
          description: Dish not found
          content:
            text/plain:
              schema:
                type: string
              example: Dish id is not found
components:
  parameters:
    IdentifierPathVariable:
      in: path
      name: id
      schema:
        type: integer
      required: true
    AtQueryParameter:
      in: query
      name: at
      schema:
        type: string
        format: date-time
      required: true
    UnitQueryParameter:
      in: query
      name: unit
      schema:
        type: string
        enum:
          - PCS
          - KG
          - L
      required: true
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: laitue
        category:
          type: string
          enum:
            - VEGETABLE
            - ANIMAL
            - MARINE
            - DAIRY
            - OTHER
          example: VEGETABLE
        price:
          type: number
          format: double
          example: 800.0
    StockValue:
      properties:
        quantity:
          type: number
          format: double
          example: 5.0
        unit:
          type: string
          enum:
            - PCS
            - KG
            - L
          example: KG
    Dish:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Poulet rôti
        selling_price:
          type: number
          format: double
          example: 3000.0
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/Ingredient"










